package motherteresa;
/*===========================================================================*
 *                                                                           *
 *  state.java     description...                                            *
 *                                                                           *
 *  Written:        3/10/02   Hein Badenhorst                                *
 *  Revised:        3/10/02                                                  *
 *                                                                           *
 *  Skeleton generated by LIBERO 2.30 on  2 Oct, 2003,  9:44.                *
 *===========================================================================*/
import java.awt.*;
import java.applet.*;
import java.net.*;
import java.util.*;
import java.io.*;


public class MenuStateMachineStubs extends MenuStateMachine
{
	private int eventNumber = 0;
	private ArrayList methodItems = null;

///////////////////////////   C O N T R U C T O R   ///////////////////////////

public MenuStateMachineStubs ()
{
    super.init();
    menu_execute();
}


//////////////////////////////////   M A I N   ////////////////////////////////

public int menu_execute ()//(String args[])
{
    int feedback;
    methodItems = new ArrayList(5);
    feedback = execute ();
    return (feedback);
}


//////////////////////////   INITIALISE THE PROGRAM   /////////////////////////

public void initialise_the_program ()
{
    the_next_event = 0;
}

public void setEventNumber(int eventNum)
{
   super.setEvent(eventNum);
   eventNumber = eventNum;
}


////////////////////////////   GET EXTERNAL EVENT   ///////////////////////////

public void get_external_event ()
{
    the_next_event = eventNumber;
}

public ArrayList getMethodItems()
{
    return methodItems;
}

//%START MODULE

////////////////////////   ALLERGIES CAPTURE DISPLAY   ////////////////////////

public void allergies_capture_display ()
{
   methodItems.add((Object)Integer.toString(InfoManager.CAPTURE_ALLERGIES));
}


////////////////////////   ASSESMENT CAPTURE DISPLAY   ////////////////////////

public void assesment_capture_display ()
{
   methodItems.add((Object)Integer.toString(InfoManager.CAPTURE_ASSESMENT));
}


/////////////////////////   DISPLAY ALLERGIES DETAIL   ////////////////////////

public void display_allergies_detail ()
{
   methodItems.add((Object)Integer.toString(InfoManager.DISPLAY_ALLERGIES));
}


/////////////////////////   DISPLAY ASSESMENT DETAIL   ////////////////////////

public void display_assesment_detail ()
{
   methodItems.add((Object)Integer.toString(InfoManager.DISPLAY_ASSESMENT));
}


////////////////////   DISPLAY CURRENT COMPLAINT CAPTURE   ////////////////////

public void display_current_complaint_capture ()
{
   methodItems.add((Object)Integer.toString(InfoManager.CAPTURE_COMPLAINT));
}


/////////////////////   DISPLAY CURRENT COMPLAINT DETAIL   ////////////////////

public void display_current_complaint_detail ()
{
   methodItems.add((Object)Integer.toString(InfoManager.DISPLAY_COMPLAINT));
}


////////////////////////   DISPLAY EXAMINATION DETAIL   ///////////////////////

public void display_examination_detail ()
{
  methodItems.add((Object)Integer.toString(InfoManager.DISPLAY_EXAMINATION));
}


//////////////////////   DISPLAY FAMILY HISTORY DETAIL   //////////////////////

public void display_family_history_detail ()
{
  methodItems.add((Object)Integer.toString(InfoManager.DISPLAY_FAMILY_HISTORY));
}


//////////////////////   DISPLAY FINAL DIAGNOSES DETAIL   /////////////////////

public void display_final_diagnoses_detail ()
{
  methodItems.add((Object)Integer.toString(InfoManager.DISPLAY_FINAL_DIAGNOSES));
}


///////////////////   DISPLAY OCCUPATIONAL HISTORY DETAIL   ///////////////////

public void display_occupational_history_detail ()
{
  methodItems.add((Object)Integer.toString(InfoManager.DISPLAY_OCCUPATIONAL_HISTORY));
}


//////////////////////   DISPLAY PATIENT BASIC CAPTURE   //////////////////////

public void display_patient_basic_capture ()
{
  methodItems.add((Object)Integer.toString(InfoManager.CAPTURE_BASIC));
}


///////////////////////   DISPLAY PATIENT BASIC DETAIL   //////////////////////

public void display_patient_basic_detail ()
{
  methodItems.add((Object)Integer.toString(InfoManager.DISPLAY_BASIC));
}


///////////////////////////   DISPLAY PLAN DETAIL   ///////////////////////////

public void display_plan_detail ()
{
  methodItems.add((Object)Integer.toString(InfoManager.DISPLAY_PLAN));
}


/////////////////   DISPLAY PREVIOUS MEDICAL HISTORY CAPTURE   ////////////////

public void display_previous_medical_history_capture ()
{
  methodItems.add((Object)Integer.toString(InfoManager.CAPTURE_MEDICAL_HISTORY));
}


/////////////////   DISPLAY PREVIOUS MEDICAL HISTORY DETAIL   /////////////////

public void display_previous_medical_history_detail ()
{
  methodItems.add((Object)Integer.toString(InfoManager.DISPLAY_MEDICAL_HISTORY));
}


////////////////   DISPLAY PREVIOUS SURGICAL HISTORY CAPTURE   ////////////////

public void display_previous_surgical_history_capture ()
{
  methodItems.add((Object)Integer.toString(InfoManager.CAPTURE_SURGICAL_HISTORY));
}


/////////////////   DISPLAY PREVIOUS SURGICAL HISTORY DETAIL   ////////////////

public void display_previous_surgical_history_detail ()
{
  methodItems.add((Object)Integer.toString(InfoManager.DISPLAY_SURGICAL_HISTORY));
}


//////////////////////   DISPLAY SOCIAL HISTORY DETAIL   //////////////////////

public void display_social_history_detail ()
{
  methodItems.add((Object)Integer.toString(InfoManager.DISPLAY_SOCIAL_HISTORY));
}


/////////////////////   DISPLAY SYSTEMIC ENQUIRY CAPTURE   ////////////////////

public void display_systemic_enquiry_capture ()
{
  methodItems.add((Object)Integer.toString(InfoManager.CAPTURE_SYSTEMIC));
}


/////////////////////   DISPLAY SYSTEMIC ENQUIRY DETAIL   /////////////////////

public void display_systemic_enquiry_detail ()
{
    methodItems.add((Object)Integer.toString(InfoManager.DISPLAY_SYSTEMIC));
}


//////////////////////   DISPLAY TRAVEL HISTORY DETAIL   //////////////////////

public void display_travel_history_detail ()
{
  methodItems.add((Object)Integer.toString(InfoManager.DISPLAY_TRAVEL_HISTORY));
}


/////////////////////////   DISPLAY TREATMENT DETAIL   ////////////////////////

public void display_treatment_detail ()
{
  methodItems.add((Object)Integer.toString(InfoManager.DISPLAY_TREATMENT));
}


///////////////////////   EXAMINATION CAPTURE DISPLAY   ///////////////////////

public void examination_capture_display ()
{
  methodItems.add((Object)Integer.toString(InfoManager.CAPTURE_EXAMINATION));
}


//////////////////////   FAMILY HISTORY CAPTURE DISPLAY   /////////////////////

public void family_history_capture_display ()
{
  methodItems.add((Object)Integer.toString(InfoManager.CAPTURE_FAMILY_HISTORY));
}


/////////////////////   FINAL DIAGNOSES CAPTURE DISPLAY   /////////////////////

public void final_diagnoses_capture_display ()
{
  methodItems.add((Object)Integer.toString(InfoManager.CAPTURE_FINAL_DIAGNOSES));
}


///////////////////   OCCUPATIONAL HISTORY CAPTURE DISPLAY   //////////////////

public void occupational_history_capture_display ()
{
  methodItems.add((Object)Integer.toString(InfoManager.CAPTURE_OCCUPATIONAL_HISTORY));
}


///////////////////////////   PLAN CAPTURE DISPLAY   //////////////////////////

public void plan_capture_display ()
{
  methodItems.add((Object)Integer.toString(InfoManager.CAPTURE_PLAN));
}


//////////////////////   SOCIAL HISTORY CAPTURE DISPLAY   /////////////////////

public void social_history_capture_display ()
{
  methodItems.add((Object)Integer.toString(InfoManager.CAPTURE_SOCIAL_HISTORY));
}


//////////////////////   TRAVEL HISTORY CAPTURE DISPLAY   /////////////////////

public void travel_history_capture_display ()
{
  methodItems.add((Object)Integer.toString(InfoManager.CAPTURE_TRAVEL_HISTORY));
}


////////////////////////   TREATMENT CAPTURE DISPLAY   ////////////////////////

public void treatment_capture_display ()
{
  methodItems.add((Object)Integer.toString(InfoManager.CAPTURE_TREATMENT));
}


//%END MODULE
}
