package motherteresa;
/*===========================================================================*
 *                                                                           *
 *  NewMenuStateMachineStubs .java   description...                                            *
 *                                                                           *
 *  Written:        3/11/14   Hein Badenhorst                                *
 *  Revised:        3/11/14                                                  *
 *                                                                           *
 *  Skeleton generated by LIBERO 2.30 on 14 Nov, 2003, 10:57.                *
 *===========================================================================*/
import java.awt.*;
import java.applet.*;
import java.net.*;
import java.util.*;
import java.io.*;

public class NewMenuStateMachineStubs extends NewMenuStateMachine
{
    private int eventNumber = 0;
    private ArrayList methodItems = null;

///////////////////////////   C O N T R U C T O R   ///////////////////////////

public NewMenuStateMachineStubs ()
{
    super.init();
    newmenu_execute();
}

//////////////////////////////////   M A I N   ////////////////////////////////

public int newmenu_execute ()
{
    int feedback;
    methodItems = new ArrayList(5);
    feedback = execute ();
    return (feedback);
}


//////////////////////////   INITIALISE THE PROGRAM   /////////////////////////

public void initialise_the_program ()
{
    the_next_event = 0;
}

public void setEventNumber(int eventNum)
{
   super.setEvent(eventNum);
   eventNumber = eventNum;
}


////////////////////////////   GET EXTERNAL EVENT   ///////////////////////////

public void get_external_event ()
{
    the_next_event = eventNumber;
}

public ArrayList getMethodItems()
{
    return methodItems;
}

//%START MODULE

//////////////////////   DISPLAY PATIENT BASIC DETAILS   //////////////////////

public void display_patient_basic_details ()
{
  methodItems.add((Object)Integer.toString(InfoManager.FOLLOWUP_DISPLAY_BASIC));
}


//////////////////////   DISPLAY PATIENT CURRENT STATUS   /////////////////////

public void display_patient_current_status ()
{
  methodItems.add((Object)Integer.toString(InfoManager.FOLLOWUP_CURRENT_STATUS));
}


///////////////////////////   DISPLAY PLAN DETAIL   ///////////////////////////

public void display_plan_detail ()
{
  methodItems.add((Object)Integer.toString(InfoManager.FOLLOWUP_DISPLAY_PLAN));
}


///////////////////////   EXAMINATION CAPTURE DISPLAY   ///////////////////////

public void examination_capture_display ()
{
  methodItems.add((Object)Integer.toString(InfoManager.FOLLOWUP_CAPTURE_EXAMINATION));
}


/////////////////////   FINAL DIAGNOSES CAPTURE DISPLAY   /////////////////////

public void final_diagnoses_capture_display ()
{
  methodItems.add((Object)Integer.toString(InfoManager.FOLLOWUP_CAPTURE_FINAL_DIAGNOSES));
}


//////////////////////   NEW COMPLAINT CAPTURE DISPLAY   //////////////////////

public void new_complaint_capture_display ()
{
  methodItems.add((Object)Integer.toString(InfoManager.FOLLOWUP_CAPTURE_COMPLAINT));
}


///////////////////////////   PLAN CAPTURE DISPLAY   //////////////////////////

public void plan_capture_display ()
{
  methodItems.add((Object)Integer.toString(InfoManager.FOLLOWUP_CAPTURE_PLAN));
}


/////////////////////   UPDATE DISPLAY COMPLAINT DETAIL   /////////////////////

public void update_display_complaint_detail ()
{
  methodItems.add((Object)Integer.toString(InfoManager.FOLLOWUP_DISPLAY_COMPLAINT));
}


////////////////////   UPDATE DISPLAY EXAMINATION DETAIL   ////////////////////

public void update_display_examination_detail ()
{
  methodItems.add((Object)Integer.toString(InfoManager.FOLLOWUP_DISPLAY_EXAMINATION));
}


//////////////////   UPDATE DISPLAY FINAL DIAGNOSES DETAIL   //////////////////

public void update_display_final_diagnoses_detail ()
{
  methodItems.add((Object)Integer.toString(InfoManager.FOLLOWUP_DISPLAY_FINAL_DIAGNOSES));
}


//%END MODULE
}
